{
 "title": "DSE Cluster",
 "tags": [ "dse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "by", "label": "Group By", "query": "cluster,dc,rack,instance" },
   { "name": "rate", "label": "Rate", "query": "1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(collectd_cpu_total, cluster)"
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": "label_values(collectd_cpu_total, dc)"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "label_values(collectd_cpu_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\"}, rack)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values(dse_table_read_latency{cluster=~\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(dse_table_read_latency{keyspace=~\"$keyspace\"}, table)"
   },
   {
    "name": "instance",
    "query": "label_values(collectd_cpu_total{cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "content": "<a href=\"https://www.datastax.com\" target=\"new\"><img src=\"https://www.datastax.com/sites/default/files/content/graphics/logo/DS-logo-2019-White.png\"/></a>"
  },
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Up",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(dse_compaction_completed_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"} >= 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Nodes Down",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(absent(sum(rate(dse_compaction_completed_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[2m])))) OR vector(0)"
      }
     ]
    },
    {
     "title": "Compactions / $rate",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(dse_compaction_completed_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
      }
     ]
    },
    {
     "title": "Requests / $rate",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
      }
     ]
    },
    {
     "title": "Dropped Messages / $rate",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(dse_table_dropped_mutations_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
      }
     ]
    },
    {
     "title": "Clients Connected",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(dse_client_connected_native_clients{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"})"
      }
     ]
    },
    {
     "title": "Client Timeouts / $rate",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(dse_client_request_timeouts_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
      }
     ]
    },
    {
     "title": "Total Hints",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(dse_storage_hints_on_disk_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"})"
      }
     ]
    },
    {
     "title": "Live Data Size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(dse_table_live_disk_space_used_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Coordinator Metrics (no keyspace/table filters apply)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Requests Served / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    }
   ]
  },
  {
   "title": "Clients Connected / $by",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dse_client_connected_native_clients{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Client Timeouts / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_timeouts_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Writes / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$instance\", request_type=~\".*write.*\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    }
   ]
  },
  {
   "title": "Coordinator Write Latency / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\",request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P50 "
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\",request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\",request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\",request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\",request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P99"
    },
    {
     "expr": "histogram_quantile(0.099, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\",request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P999"
    }
   ]
  },
  {
   "title": "Reads / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~'${instance}', cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\",request_type=\"read\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    }
   ]
  },
  {
   "title": "Coordinator Read Latency / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P50 "
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P999"
    }
   ]
  },
  {
   "title": "Range Slices / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\",request_type=~\".*slice.*\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    }
   ]
  },
  {
   "title": "Coordinator Range Read Latency / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{instance=~\"${instance:raw}\", request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P50 "
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P999"
    }
   ]
  },
  {
   "title": "View Write / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\",request_type=~\".*view_write.*\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    }
   ]
  },
  {
   "title": "Coordinator View Write Latency / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P50 "
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"read\", cluster=~\"cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P999"
    }
   ]
  },
  {
   "title": "Coordinator CAS (no keyspace/table filters apply)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "CAS Write / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\",request_type=~\".*cas_write.*\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    }
   ]
  },
  {
   "title": "Coordinator CAS Write Latency / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P50 "
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P999"
    }
   ]
  },
  {
   "title": "CAS Read / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\",request_type=~\".*cas_read.*\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    }
   ]
  },
  {
   "title": "Coordinator CAS Read Latency / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P50 "
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_read\", cluster=~\"cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{instance=~\"$instance\", request_type=\"cas_read\", cluster=~\"cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} P999"
    }
   ]
  },
  {
   "title": "Table Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coordinator Table Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_coordinator_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_coordinator_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_coordinator_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_coordinator_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_coordinator_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_coordinator_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Local Table Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_read_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Local Table Write Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_write_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_write_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_write_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_write_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_write_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_write_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Coordinator Table Range Scan Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_coordinator_scan_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_coordinator_scan_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_coordinator_scan_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_coordinator_scan_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_coordinator_scan_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_coordinator_scan_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Local Table Range Scan Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_range_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_range_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_range_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_range_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_range_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_range_latency_bucket{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Memtable Space  $keyspace.$table / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(dse_table_memtable_off_heap_size{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}} : Off Heap"
      },
      {
       "expr": "sum(dse_table_memtable_on_heap_size{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}} : On Heap"
      },
      {
       "expr": "sum(dse_table_memtable_live_data_size{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}} : Data Size"
      },
      {
       "expr": "sum(idelta(dse_table_memtable_switch_count_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}} : Flushes"
      },
      {
       "expr": "sum(idelta(dse_table_pending_flushes_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}} : Pending Flushes"
      }
     ]
    },
    {
     "title": "SSTables Per Read / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(dse_table_ss_tables_per_read_histogram{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=~\".\\\\d+\"}) by (quantile, instance)",
       "legendFormat": "Node {{instance}} P{{quantile}}"
      }
     ]
    },
    {
     "title": "Tombstones Scanned / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dse_table_tombstone_scanned_histogram{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=~\".\\\\d+\"}) by (quantile, instance)",
       "legendFormat": "{{instance}} : P{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live Disk Space Used / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(dse_table_total_disk_space_used_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Storage Load / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(dse_storage_load_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Total Hints / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dse_storage_total_hints_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Hints on Disk / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_storage_hints_on_disk_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CQL Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prepared Statement Ratio / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(dse_cql_prepared_statements_ratio{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Prepared Statements / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(dse_cql_prepared_statements_count{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Executed Prepared Statements / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_cql_prepared_statements_executed_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM G1 Eden Space Used / node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dse_jvm_memory_pool_used{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.memory.pools.g1_eden_space.used\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM G1 Old Gen Used / node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dse_jvm_memory_pool_used{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.memory.pools.g1_old_gen.used\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM G1 Survivor Space / node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dse_jvm_memory_pool_used{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.memory.pools.g1_survivor_space.used\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Young Gen / node / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_time{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_young_generation.time\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Old Gen / node / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_time{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_old_generation.time\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Old Gen Count / node / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_count{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_old_generation.count\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Old Gen Count / node / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_count{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_young_generation.count\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Compactions / node / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(dse_compaction_pending_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Completed Compactions / node / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_compaction_completed_tasks{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Compacted Bytes / node / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_compaction_bytes_compacted_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hint Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hint Delays / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_hints_hint_delays_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Hints Succeeded / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_hints_hints_succeeded_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Hints Failed / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_hints_hints_failed_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeSync Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Pages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dse_node_sync_full_in_sync_pages_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\",keyspace=~\"$keyspace\"}[$rate])) by (instance, dse) ",
       "legendFormat": "Node {{instance}} {{dse}}"
      }
     ]
    },
    {
     "title": "Node Sync All",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate({__name__=~\".+node_sync.+\", instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\",keyspace=~\"$keyspace\"}[$rate])) by (instance, dse) ",
       "legendFormat": "Node {{instance}} {{dse}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repair Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repairs Completed / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_table_repair_jobs_completed_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (table, $by)",
       "legendFormat": "{{ $by }} : {{ table }}"
      }
     ]
    },
    {
     "title": "Read Repair Requests / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_table_read_repair_requests_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (table, $by)",
       "legendFormat": "{{ $by }} : {{ table }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Streaming Incoming Bytes / $by / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(dse_streaming_incoming_bytes_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Streaming Outgoing Bytes / $by / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(dse_streaming_outgoing_bytes_total{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunk Cache Hit Rate / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(dse_cache_hit_rate{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", cache_name=\"chunk_cache\"}) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Counter Cache Hit Rate / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "dse_cache_hit_rate{ cache_name=\"counter_cache\"}",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Key Cache Hit Rate / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(dse_cache_hit_rate{instance=~\"$instance\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", cache_name=\"key_cache\"}) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPC All Tasks Completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dse_thread_pools_completed_tasks{pool_name=~\"tpc_.*\", cluster=~\"$cluster\", dc=~\"$dc\", instance=~\"$instance\"}[$rate])) by (pool_name, $by)",
       "legendFormat": "{{pool_name}} {{$instance}}"
      }
     ]
    },
    {
     "title": "TPC All Tasks Pending",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dse_thread_pools_pending_tasks{pool_name=~\"tpc_.*\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}[$rate])) by (pool_name, $by)",
       "legendFormat": "{{pool_name}}"
      }
     ]
    },
    {
     "title": "TPC All Tasks Blocked",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dse_thread_pools_currently_blocked_tasks_total{pool_name=~\"tpc_.*\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}[$rate])) by (pool_name, $by)",
       "legendFormat": "{{pool_name}}"
      }
     ]
    },
    {
     "title": "TPC Backpressure",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(dse_thread_pools_total_backpressure_counted_tasks_gauge{rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}) by ($by)",
       "legendFormat": "{{pool_name}}"
      },
      {
       "expr": "sum(dse_thread_pools_total_backpressure_delayed_tasks_gauge{rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}) by ($by)"
      }
     ]
    },
    {
     "title": "TPC Read Tasks Active",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dse_thread_pools_active_tasks{pool_name=~\"tpc_.*read.*\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}[$rate])) by (pool_name, $by)",
       "legendFormat": "{{pool_name}}"
      }
     ]
    },
    {
     "title": "TPC Write Tasks Active [max pool size]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dse_thread_pools_active_tasks{pool_name=~\"tpc_.*write.*\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}[$rate])) by (pool_name, $by)",
       "legendFormat": "{{pool_name}}"
      }
     ]
    },
    {
     "title": "TPC NodeSync Tasks Active",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "dse_thread_pools_active_tasks{pool_name=~\"tpc_all_nodesync_validation\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}"
      },
      {
       "expr": "dse_thread_pools_active_tasks{pool_name=~\"tpc_other_read_range_nodesync\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flushes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flushes Pending",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dse_table_pending_flushes_total{rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\", table=~\"$table\", keyspace=~\"$keyspace\"}) by ($by)"
      },
      {
       "expr": "sum(dse_keyspace_pending_flushes{rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\", table=~\"$table\", keyspace=~\"$keyspace\"}) by ($by)"
      }
     ]
    },
    {
     "title": "Bytes Flushed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dse_table_bytes_flushed_total{rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\", table=~\"$table\", keyspace=~\"$keyspace\"}[$rate])) by ($by)"
      }
     ]
    },
    {
     "title": "Memtable Flusher TP Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(dse_thread_pools_pending_tasks{pool_name=~\"memtable_flush_writer\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (pool_name, $by)",
       "legendFormat": "pending {{pool_name}}"
      },
      {
       "expr": "sum(dse_thread_pools_active_tasks{pool_name=~\"memtable_flush_writer\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (pool_name, $by)",
       "legendFormat": "active {{pool_name}}"
      },
      {
       "expr": "sum(dse_thread_pools_max_pool_size{pool_name=~\".+memtable.+\", rack=~\"$rack\", dc=~\"$dc\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (pool_name, $by)",
       "legendFormat": "max_allowed {{pool_name}}"
      }
     ]
    }
   ]
  }
 ]
}