---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: cass-operator
spec:
  channel: alpha
  name: grafana-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
