apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: cluster-dse-options
spec:
  clientAuth:
    secretNames:
      - ca-cert
    clientAuthType: RequireAndVerifyClientCert
  sniStrict: true