apiVersion: v1
kind: Service
metadata:
  name: studio
  namespace: cass-operator
  labels:
    app: studio
spec:
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    app: studio
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio
  namespace: cass-operator
  labels:
    app: studio  
spec:
  selector:
    matchLabels:
      app: studio
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: studio
        tier: frontend
    spec:
      containers:
      - image: datastax/dse-studio:6.8.2
        name: studio
        env:
        - name: DS_LICENSE
          value: accept
        ports:
        - containerPort: 9091
          name: studio
